// <auto-generated />
using System;
using GitHubIntelligenceService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHubIntelligenceService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216123039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GitHubIntelligenceService.Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("GitHubIntelligenceService.Domain.Entities.RepositoryAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Issues")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("GitHubIntelligenceService.Domain.Entities.Developer", b =>
                {
                    b.OwnsOne("GitHubIntelligenceService.Domain.ValueObjects.DeveloperScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("DeveloperId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("ActivityScore")
                                .HasColumnType("REAL");

                            b1.Property<double>("PopularityScore")
                                .HasColumnType("REAL");

                            b1.Property<double>("QualityScore")
                                .HasColumnType("REAL");

                            b1.Property<string>("SeniorityLevel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("TotalScore")
                                .HasColumnType("REAL");

                            b1.HasKey("DeveloperId");

                            b1.ToTable("Developers");

                            b1.WithOwner()
                                .HasForeignKey("DeveloperId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("GitHubIntelligenceService.Domain.Entities.RepositoryAnalysis", b =>
                {
                    b.HasOne("GitHubIntelligenceService.Domain.Entities.Developer", null)
                        .WithMany("Repositories")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GitHubIntelligenceService.Domain.Entities.GitHubRepository", "Repository", b1 =>
                        {
                            b1.Property<Guid>("RepositoryAnalysisId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Forks")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("IssuesCount")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Language")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("LastPushedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Stars")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RepositoryAnalysisId");

                            b1.ToTable("Repositories");

                            b1.WithOwner()
                                .HasForeignKey("RepositoryAnalysisId");
                        });

                    b.Navigation("Repository")
                        .IsRequired();
                });

            modelBuilder.Entity("GitHubIntelligenceService.Domain.Entities.Developer", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
